lutece-secteur-public/gru-plugin-appointment

src/java/fr/paris/lutece/plugins/appointment/web/CommentJspBean.java

Fix conflict between current comment and previous one.

Rendezvous 538 fix bad comment editing

---

src/java/fr/paris/lutece/plugins/appointment/business/comment/Comment.java
webapp/WEB-INF/templates/admin/plugins/appointment/appointment/appointment_form_list_open_slots_grouped.html
webapp/WEB-INF/templates/admin/plugins/appointment/appointment/manage_appointments_calendar.html
webapp/WEB-INF/templates/admin/plugins/appointment/appointment/manage_appointments_multislot_calendar.html

Fix fullcalendar comments display issue.

Rendezvous 539 fix fullcalendar comments display issue

---

webapp/WEB-INF/templates/admin/plugins/appointment/appointment/manage_appointments_calendar.html
webapp/WEB-INF/templates/admin/plugins/appointment/appointment/manage_appointments_multislot_calendar.html

RENDEZVOUS-539 fix calendar comment end display

---

src/test/java/fr/paris/lutece/plugins/appointment/service/TimeSlotServiceTest.java
src/test/java/fr/paris/lutece/plugins/appointment/service/WeekDefinitionServiceTest.java
src/test/java/fr/paris/lutece/plugins/appointment/service/WorkingDayServiceTest.java

Fix weekdefinitions tests 

---

src/java/fr/paris/lutece/plugins/appointment/business/appointment/Appointment.java

RENDEZVOUS-747 appointment's user firstname and lastname not checked

---

src/sql/plugins/appointment/core/init_core_appointment.sql
src/sql/plugins/appointment/upgrade/update_db_appointment_2.1.0-3.0.0.sql

Currently, the construction of a database for the Rendez-vous application via ANT does not provide all the tables necessary for the good functioning of the application.
The init, create and update scripts concerned must be corrected.

Redmine-25159  Be able to build a database from the generic Rendezvous pom

---

src/java/fr/paris/lutece/plugins/appointment/service/AppointmentExecutorService.java
src/java/fr/paris/lutece/plugins/appointment/service/AppointmentUtilities.java

https://dev.lutece.paris.fr/sonar/project/issues?id=fr.paris.lutece.plugins%3Aplugin-appointment&resolved=false&rules=squid%3AS2142&types=BUG

Rendezvous sonar bug major interrupted exception should not be ignored 

---

webapp/WEB-INF/templates/admin/plugins/appointment/slots/manage_annual_calendar.html

https://dev.lutece.paris.fr/bugtracker/issues/25161

Redmine 25161 in the manage annual calendar view remove the number in the logo indicating the days with specificities

---

src/java/fr/paris/lutece/plugins/appointment/web/AppointmentApp.java

https://dev.lutece.paris.fr/bugtracker/issues/25265

Redmine-25265-fix_FO_Control_on_nbPlacesToTake 

---

src/java/fr/paris/lutece/plugins/appointment/service/AppointmentService.java

https://dev.lutece.paris.fr/bugtracker/issues/25338

RENDEZVOUS_25338_The_workflow_task_Notify_an_administrator_of_an_appointment_is_not_functional_in_V3 

---

src/sql/plugins/genericattributes/plugin/init_db_genericattributes_appointment.sql
src/sql/plugins/genericattributes/plugin/upgrade/update_db_generic_attributes_appointment_2.0.0-2.4.3.sql

This PR only contains SQL related changes, and will replace the following pull request:
- https://github.com/lutece-secteur-public/gru-plugin-appointment/pull/99
The remaining changes for the Redmine issue #25341 will be done in a future PR.

REDMINE 25341 - Improve the management of Generic attributes in Rendez-vous

---

src/java/fr/paris/lutece/plugins/appointment/service/AppointmentService.java

PR already reviewed and merged : #98 
The development I did in this PR should serve as a production patch. They requested me to create a dedicated branch from the master branch, and they specifically mentioned generating a JAR file with the plugin "appointment" including the necessary correction.

Redmine 25338 [Patch]_The_wf_task_Notify_an_administrator_of_an_appointment_is_not_functional_in_V3

---

webapp/WEB-INF/templates/admin/plugins/appointment/appointment_commons.html

Redmine ticket : https://dev.lutece.paris.fr/bugtracker/issues/25160

Redmine25160 : creation and modification of a comment no mailing list by default

---

src/java/fr/paris/lutece/plugins/appointment/business/appointment/AppointmentDAO.java
webapp/WEB-INF/templates/admin/plugins/appointment/appointment/manage_appointments.html

Fixed the date filters and the phone number's value processing (to properly handle NULL and empty values)

Redmine 25396 - Fixed search filter by date error on some filters

---

webapp/WEB-INF/templates/skin/plugins/appointment/appointment_nb_places_to_take_form.html

Redmine ticket : https://dev.lutece.paris.fr/bugtracker/issues/25844

Redmine 25844 : [FO] Change labels for "number of people". 

---

webapp/WEB-INF/templates/skin/plugins/appointment/entries/html_code_entry_type_date.html

Redmine 19048 [FO} the date field is reset in case of an error in another field

---

src/sql/plugins/appointment/plugin/create_db_appointment.sql
src/sql/plugins/appointment/upgrade/update_db_appointment_3.0.0-3.0.7.sql

SQL Script to manually correct the "stuck" forms :
_UPDATE appointment_form SET nb_consecutive_slots = 1
WHERE nb_consecutive_slots = 0;_

LUT-25895 : [BO] An incorrect management rule has been added to the settings for creating typical weeks

---

webapp/WEB-INF/templates/admin/plugins/appointment/appointment/manage_appointments.html

https://dev.lutece.paris.fr/bugtracker/issues/25154

LUT-25154: Refactor label retrieval in 'Appointment management by filter' search filter to use internationalized values from resource files.

---

src/java/fr/paris/lutece/plugins/appointment/service/AppointmentPlugin.java
src/java/fr/paris/lutece/plugins/appointment/web/file/AppointmentFormIconService.java

https://dev.lutece.paris.fr/bugtracker/issues/26856

LUT-26856: Implement AppointmentFormIconService

---

src/java/fr/paris/lutece/plugins/appointment/service/AppointmentUtilities.java
src/java/fr/paris/lutece/plugins/appointment/web/AppointmentApp.java
src/java/fr/paris/lutece/plugins/appointment/web/AppointmentJspBean.java
src/sql/plugins/appointment/upgrade/update_db_appointment_3.0.7-3.0.8.sql
src/test/java/fr/paris/lutece/plugins/appointment/service/AppointmentUtilitiesTest.java

An SQL script was added to update a user's phone number and set the correct value, in case the user was created before this fix

LUT-26857: Update the appointment's creation process to retrieve the user's phone number from a generic attribute

---

src/java/fr/paris/lutece/plugins/appointment/business/portlet/AppointmentPortlet.java
src/java/fr/paris/lutece/plugins/appointment/web/AppointmentApp.java

- Generalized the use of the `getXpage()` method
- Updated the name of the method `getMyAppointmentsXPage()`:
- Now named `getMyAppointmentsHtml()` to reflect more accurately the content returned

LUT-25261: Updated method returns and method names

---

webapp/WEB-INF/templates/admin/plugins/appointment/entries/modify_entry_type_geolocation.html
webapp/WEB-INF/templates/skin/plugins/appointment/entries/html_code_entry_type_geolocation.html

https://dev.lutece.paris.fr/bugtracker/issues/26825

LUT-26825: fix geolocation field and autocomplete

---

webapp/WEB-INF/templates/admin/plugins/appointment/entries/modify_entry_type_file.html

https://dev.lutece.paris.fr/bugtracker/issues/27716

LUT-27716 : Remove unused genatt_field code "used_in_correct_form_response"

---

src/sql/plugins/genericattributes/plugin/init_db_genericattributes_appointment.sql

This PR depends on the following pull request, made on the `Plugin GenericAttributes`:
- https://github.com/lutece-platform/lutece-genattrs-plugin-genericattributes/pull/73

LUT-28045: Updated the initialisation of the Generic Attributes to avoid the use of hard values for the IDs

---

webapp/WEB-INF/templates/skin/plugins/appointment/calendar/appointment_form_calendar.html

https://dev.lutece.paris.fr/bugtracker/issues/28597

LUT-28597 : Fix popover issue for Bootstrap 5 compatibility in calendar

---

webapp/WEB-INF/templates/admin/plugins/appointment/appointmentform/modify_appointmentform_entries.html
webapp/css/admin/plugins/appointment/appointment.css

https://dev.lutece.paris.fr/bugtracker/issues/28819

LUT-28819 : Fix button size and spacing in field type list
